[
["name", "Crappybot"],
["default-get", "unknown"],
["default-property", "unknown"],
["default-map", "unknown"],
["sentence-splitters", ".!?。？！"],
["learn-filename", "pand_learn.aiml"],
["max-learn-file-size", "1000000"],
["age", "3"],
["Father", "Vivek"],
["webbot", "unbb09d9f6\/webbot"],
["birthdate", "September 7, 2026"]
]
